### ISSUE TITLE
Texto do botão de atualizar senha está errado

### ISSUE THREAD

**Issue by arthur-es** [arthur-es/dominios-de-software#4]
![image](https://user-images.githubusercontent.com/37699234/160290207-827bc756-627d-48f3-bbad-6eb90bb0c08e.png)

Depois que eu clico nesse link vou para a tela de atualizar a minha senha 

E no texto do botão está escrito "Enviar por e-mail"

**Comment by felipelagares** [comment]
concluida na branch dev e na felipe
